-- Clear existing words in quiz_items
DELETE FROM public.quiz_items WHERE category = 'words';

-- Insert all words
INSERT INTO public.quiz_items (category, "character", romaji, kana, meaning, type, has_kanji, lesson) VALUES
('words', 'こんにちは', ARRAY['konnichiwa'], 'こんにちは', 'Halo / Selamat siang', 'word', false, 'Pelajaran 1'),
('words', 'ありがとう', ARRAY['arigatou', 'arigato'], 'ありがとう', 'Terima kasih', 'word', false, 'Pelajaran 1'),
('words', 'すみません', ARRAY['sumimasen'], 'すみません', 'Permisi / Maaf', 'word', false, 'Pelajaran 1'),
('words', 'はい', ARRAY['hai'], 'はい', 'Ya', 'word', false, 'Pelajaran 1'),
('words', 'いいえ', ARRAY['iie'], 'いいえ', 'Tidak', 'word', false, 'Pelajaran 1'),
('words', 'さようなら', ARRAY['sayounara', 'sayonara'], 'さようなら', 'Selamat tinggal', 'word', false, 'Pelajaran 1'),
('words', 'わたし', ARRAY['watashi'], 'わたし', 'saya', 'word', false, 'Pelajaran 1'),
('words', 'あなた', ARRAY['anata'], 'あなた', 'Anda / kamu', 'word', false, 'Pelajaran 1'),
('words', 'あの人', ARRAY['anohito', 'ano hito'], 'あのひと', 'orang itu', 'word', true, 'Pelajaran 1'),
('words', 'あの方', ARRAY['anokata', 'ano kata'], 'あのかた', 'beliau (sopan)', 'word', true, 'Pelajaran 1'),
('words', '～さん', ARRAY['san', '~san'], '～さん', 'Sdr. ~, Bapak ~, Ibu ~', 'word', false, 'Pelajaran 1'),
('words', '～ちゃん', ARRAY['chan', '~chan'], '～ちゃん', 'akhiran panggilan anak', 'word', false, 'Pelajaran 1'),
('words', '～人', ARRAY['jin', '~jin'], '～じん', 'orang ~ (warga negara)', 'word', true, 'Pelajaran 1'),
('words', 'だれ', ARRAY['dare'], 'だれ', 'siapa', 'word', false, 'Pelajaran 1'),
('words', 'どなた', ARRAY['donata'], 'どなた', 'siapa (sopan)', 'word', false, 'Pelajaran 1'),
('words', 'おいくつ', ARRAY['oikutsu'], 'おいくつ', 'umur berapa (sopan)', 'word', false, 'Pelajaran 1'),
('words', 'はじめまして', ARRAY['hajimemashite'], 'はじめまして', 'Perkenalkan (salam kenal)', 'word', false, 'Pelajaran 1'),
('words', '～から来ました', ARRAY['kara kimashita', 'kara kimasita'], '～からきました', 'datang dari ~, berasal dari ~', 'word', true, 'Pelajaran 1'),
('words', 'どうぞよろしく', ARRAY['douzo yoroshiku', 'dozo yoroshiku'], 'どうぞよろしく', 'Salam kenal / Mohon bantuannya', 'word', false, 'Pelajaran 1'),
('words', '失礼ですが', ARRAY['shitsurei desu ga', 'sitsurei desu ga'], 'しつれいですが', 'permisi, maaf...', 'word', true, 'Pelajaran 1'),
('words', 'お名前は？', ARRAY['onamae wa', 'onamae wa?'], 'おなまえは？', 'Siapa namanya?', 'word', true, 'Pelajaran 1'),
('words', 'アメリカ', ARRAY['amerika'], 'アメリカ', 'Amerika Serikat', 'word', false, 'Pelajaran 1'),
('words', 'イギリス', ARRAY['igirisu'], 'イギリス', 'Inggris', 'word', false, 'Pelajaran 1'),
('words', 'インド', ARRAY['indo'], 'インド', 'India', 'word', false, 'Pelajaran 1'),
('words', 'インドネシア', ARRAY['indoneshia', 'indonesia'], 'インドネシア', 'Indonesia', 'word', false, 'Pelajaran 1'),
('words', 'タイ', ARRAY['tai'], 'タイ', 'Thailand', 'word', false, 'Pelajaran 1'),
('words', 'ドイツ', ARRAY['doitsu'], 'ドイツ', 'Jerman', 'word', false, 'Pelajaran 1'),
('words', 'ブラジル', ARRAY['burajiru'], 'ブラジル', 'Brasil', 'word', false, 'Pelajaran 1'),
('words', 'これ', ARRAY['kore'], 'これ', 'ini (dekat pembicara)', 'word', false, 'Pelajaran 2'),
('words', 'それ', ARRAY['sore'], 'それ', 'itu (dekat lawan bicara)', 'word', false, 'Pelajaran 2'),
('words', 'あれ', ARRAY['are'], 'あれ', 'itu (jauh dari keduanya)', 'word', false, 'Pelajaran 2'),
('words', 'この', ARRAY['kono'], 'この', '~ ini', 'word', false, 'Pelajaran 2'),
('words', 'その', ARRAY['sono'], 'その', '~ itu', 'word', false, 'Pelajaran 2'),
('words', 'あの', ARRAY['ano'], 'あの', '~ itu (jauh)', 'word', false, 'Pelajaran 2'),
('words', 'ノート', ARRAY['nooto', 'noto'], 'ノート', 'buku tulis, catatan', 'word', false, 'Pelajaran 2'),
('words', 'カード', ARRAY['kaado', 'kado'], 'カード', 'kartu', 'word', false, 'Pelajaran 2'),
('words', 'ボールペン', ARRAY['boorupen', 'borupen'], 'ボールペン', 'bolpoin', 'word', false, 'Pelajaran 2'),
('words', 'シャープペンシル', ARRAY['shaapupenshiru', 'shapupenshiru'], 'シャープペンシル', 'pensil mekanik', 'word', false, 'Pelajaran 2'),
('words', 'かぎ', ARRAY['kagi'], 'かぎ', 'kunci', 'word', false, 'Pelajaran 2'),
('words', 'かばん', ARRAY['kaban'], 'かばん', 'tas', 'word', false, 'Pelajaran 2'),
('words', 'テレビ', ARRAY['terebi'], 'テレビ', 'televisi', 'word', false, 'Pelajaran 2'),
('words', 'ラジオ', ARRAY['rajio'], 'ラジオ', 'radio', 'word', false, 'Pelajaran 2'),
('words', 'カメラ', ARRAY['kamera'], 'カメラ', 'kamera', 'word', false, 'Pelajaran 2'),
('words', 'コンピューター', ARRAY['konpyuutaa', 'konpyuta'], 'コンピューター', 'komputer, PC', 'word', false, 'Pelajaran 2'),
('words', 'いす', ARRAY['isu'], 'いす', 'kursi', 'word', false, 'Pelajaran 2'),
('words', 'コーヒー', ARRAY['koohii', 'kohi'], 'コーヒー', 'kopi', 'word', false, 'Pelajaran 2'),
('words', 'お土産', ARRAY['omiyage'], 'おみやげ', 'oleh-oleh', 'word', true, 'Pelajaran 2'),
('words', '～語', ARRAY['go', '~go'], '～ご', 'bahasa ~', 'word', true, 'Pelajaran 2'),
('words', 'そう', ARRAY['sou', 'so'], 'そう', 'begitu', 'word', false, 'Pelajaran 2'),
('words', '違います', ARRAY['chigaimasu', 'tigaimasu'], 'ちがいます', 'Bukan / Salah', 'word', true, 'Pelajaran 2'),
('words', 'そうですか', ARRAY['sou desu ka', 'soudesuka'], 'そうですか', 'O, begitu / Begitu ya', 'word', false, 'Pelajaran 2'),
('words', '先生', ARRAY['sensei'], 'せんせい', 'guru, dosen', 'word', true, 'Pelajaran 1'),
('words', '教師', ARRAY['kyoushi', 'kyoshi'], 'きょうし', 'guru, dosen (sebagai profesi)', 'word', true, 'Pelajaran 1'),
('words', '学生', ARRAY['gakusei'], 'がくせい', 'mahasiswa, siswa', 'word', true, 'Pelajaran 1'),
('words', '会社員', ARRAY['kaishain'], 'かいしゃいん', 'karyawan perusahaan', 'word', true, 'Pelajaran 1'),
('words', '社員', ARRAY['shain'], 'しゃいん', 'karyawan perusahaan (dengan nama kantor)', 'word', true, 'Pelajaran 1'),
('words', '銀行員', ARRAY['ginkouin', 'ginkoin'], 'ぎんこういん', 'pegawai bank', 'word', true, 'Pelajaran 1'),
('words', '医者', ARRAY['isha'], 'いしゃ', 'dokter', 'word', true, 'Pelajaran 1'),
('words', '研究者', ARRAY['kenkyuusha', 'kenkyusha'], 'けんきゅうしゃ', 'peneliti', 'word', true, 'Pelajaran 1'),
('words', '大学', ARRAY['daigaku'], 'だいがく', 'universitas', 'word', true, 'Pelajaran 1'),
('words', '病院', ARRAY['byouin', 'byoin'], 'びょういん', 'rumah sakit', 'word', true, 'Pelajaran 1'),
('words', '一歳', ARRAY['issai'], 'いっさい', 'umur satu tahun', 'word', true, 'Pelajaran 1'),
('words', '何歳', ARRAY['nansai'], 'なんさい', 'umur berapa', 'word', true, 'Pelajaran 1'),
('words', '韓国', ARRAY['kankoku'], 'かんこく', 'Korea Selatan', 'word', true, 'Pelajaran 1'),
('words', '中国', ARRAY['chuugoku', 'chugoku'], 'ちゅうごく', 'Cina', 'word', true, 'Pelajaran 1'),
('words', '日本', ARRAY['nihon', 'nippon'], 'にほん', 'Jepang', 'word', true, 'Pelajaran 1'),
('words', '本', ARRAY['hon'], 'ほん', 'buku', 'word', true, 'Pelajaran 2'),
('words', '辞書', ARRAY['jisho'], 'じしょ', 'kamus', 'word', true, 'Pelajaran 2'),
('words', '雑誌', ARRAY['zasshi'], 'ざっし', 'majalah', 'word', true, 'Pelajaran 2'),
('words', '新聞', ARRAY['shinbun'], 'しんぶん', 'koran, surat kabar', 'word', true, 'Pelajaran 2'),
('words', '手帳', ARRAY['techou', 'techo'], 'てちょう', 'buku agenda', 'word', true, 'Pelajaran 2'),
('words', '名刺', ARRAY['meishi'], 'めいし', 'kartu nama', 'word', true, 'Pelajaran 2'),
('words', '鉛筆', ARRAY['enpitsu'], 'えんぴつ', 'pensil', 'word', true, 'Pelajaran 2'),
('words', '時計', ARRAY['tokei'], 'とけい', 'jam, arloji', 'word', true, 'Pelajaran 2'),
('words', '傘', ARRAY['kasa'], 'かさ', 'payung', 'word', true, 'Pelajaran 2'),
('words', '車', ARRAY['kuruma'], 'くるま', 'mobil', 'word', true, 'Pelajaran 2'),
('words', '机', ARRAY['tsukue'], 'つくえ', 'meja, meja tulis', 'word', true, 'Pelajaran 2'),
('words', '英語', ARRAY['eigo'], 'えいご', 'bahasa Inggris', 'word', true, 'Pelajaran 2'),
('words', '日本語', ARRAY['nihongo'], 'にほんご', 'bahasa Jepang', 'word', true, 'Pelajaran 2'),
('words', '何', ARRAY['nan', 'nani'], 'なん', 'apa', 'word', true, 'Pelajaran 2'),
('words', '教室', ARRAY['kyoushitsu', 'kyoshitsu'], 'きょうしつ', 'ruang kelas', 'word', true, 'Pelajaran 3'),
('words', '食堂', ARRAY['shokudou', 'shokudo'], 'しょくどう', 'ruang makan, kantin', 'word', true, 'Pelajaran 3'),
('words', '事務所', ARRAY['jimusho'], 'じむしょ', 'kantor', 'word', true, 'Pelajaran 3'),
('words', '会議室', ARRAY['kaigishitsu'], 'かいぎしつ', 'ruang rapat', 'word', true, 'Pelajaran 3'),
('words', '受付', ARRAY['uketsuke'], 'うけつけ', 'meja informasi, resepsionis', 'word', true, 'Pelajaran 3'),
('words', '部屋', ARRAY['heya'], 'へや', 'kamar, ruangan', 'word', true, 'Pelajaran 3'),
('words', '階段', ARRAY['kaidan'], 'かいだん', 'tangga', 'word', true, 'Pelajaran 3'),
('words', '自動販売機', ARRAY['jidouhanbaiki', 'jidohanbaiki'], 'じどうはんばいき', 'mesin jual otomatis', 'word', true, 'Pelajaran 3'),
('words', '電話', ARRAY['denwa'], 'でんわ', 'telepon', 'word', true, 'Pelajaran 3'),
('words', '会社', ARRAY['kaisha'], 'かいしゃ', 'perusahaan', 'word', true, 'Pelajaran 3'),
('words', '靴', ARRAY['kutsu'], 'くつ', 'sepatu', 'word', true, 'Pelajaran 3'),
('words', '売り場', ARRAY['uriba'], 'うりば', 'tempat penjualan, konter', 'word', true, 'Pelajaran 3'),
('words', '地下', ARRAY['chika'], 'ちか', 'bawah tanah, basement', 'word', true, 'Pelajaran 3'),
('words', '百', ARRAY['hyaku'], 'ひゃく', 'ratus, seratus', 'word', true, 'Pelajaran 3'),
('words', '千', ARRAY['sen'], 'せん', 'ribu, seribu', 'word', true, 'Pelajaran 3'),
('words', '万', ARRAY['man'], 'まん', 'puluh ribu (10.000)', 'word', true, 'Pelajaran 3'),
('words', '起きます', ARRAY['okimasu'], 'おきます', 'bangun tidur', 'word', true, 'Pelajaran 4'),
('words', '寝ます', ARRAY['nemasu'], 'ねます', 'tidur', 'word', true, 'Pelajaran 4'),
('words', '働きます', ARRAY['hatarakimasu'], 'はたらきます', 'bekerja', 'word', true, 'Pelajaran 4'),
('words', '休みます', ARRAY['yasumimasu'], 'やすみます', 'beristirahat, libur', 'word', true, 'Pelajaran 4'),
('words', '勉強します', ARRAY['benkyoushimasu', 'benkyoshimasu'], 'べんきょうします', 'belajar', 'word', true, 'Pelajaran 4'),
('words', '終わります', ARRAY['owarimasu'], 'おわります', 'selesai', 'word', true, 'Pelajaran 4'),
('words', '銀行', ARRAY['ginkou', 'ginko'], 'ぎんこう', 'bank', 'word', true, 'Pelajaran 4'),
('words', '郵便局', ARRAY['yuubinkyoku', 'yubinkyoku'], 'ゆうびんきょく', 'kantor pos', 'word', true, 'Pelajaran 4'),
('words', '図書館', ARRAY['toshokan'], 'としょかん', 'perpustakaan', 'word', true, 'Pelajaran 4'),
('words', '美術館', ARRAY['bijutsukan'], 'びじゅつかん', 'gedung kesenian, museum seni', 'word', true, 'Pelajaran 4'),
('words', '今', ARRAY['ima'], 'いま', 'sekarang', 'word', true, 'Pelajaran 4'),
('words', '何時', ARRAY['nanji'], 'なんじ', 'jam berapa', 'word', true, 'Pelajaran 4'),
('words', '午前', ARRAY['gozen'], 'ごぜん', 'a.m. (pagi)', 'word', true, 'Pelajaran 4'),
('words', '午後', ARRAY['gogo'], 'ごご', 'p.m. (sore/malam)', 'word', true, 'Pelajaran 4'),
('words', '朝', ARRAY['asa'], 'あさ', 'pagi', 'word', true, 'Pelajaran 4'),
('words', '昼', ARRAY['hiru'], 'ひる', 'siang', 'word', true, 'Pelajaran 4'),
('words', '晩', ARRAY['ban'], 'ばん', 'malam', 'word', true, 'Pelajaran 4'),
('words', '試験', ARRAY['shiken'], 'しけん', 'ujian', 'word', true, 'Pelajaran 4'),
('words', '会議', ARRAY['kaigi'], 'かいぎ', 'rapat', 'word', true, 'Pelajaran 4'),
('words', '映画', ARRAY['eiga'], 'えいが', 'film', 'word', true, 'Pelajaran 4'),
('words', '毎日', ARRAY['mainichi'], 'まいにち', 'setiap hari', 'word', true, 'Pelajaran 4'),
('words', '学校', ARRAY['gakkou', 'gakko'], 'がっこう', 'sekolah', 'word', true, 'Pelajaran 5'),
('words', '駅', ARRAY['eki'], 'えき', 'stasiun', 'word', true, 'Pelajaran 5'),
('words', '飛行機', ARRAY['hikouki', 'hikoki'], 'ひこうき', 'pesawat terbang', 'word', true, 'Pelajaran 5'),
('words', '船', ARRAY['fune'], 'ふね', 'kapal laut', 'word', true, 'Pelajaran 5'),
('words', '電車', ARRAY['densha'], 'でんしゃ', 'kereta rel listrik', 'word', true, 'Pelajaran 5'),
('words', '地下鉄', ARRAY['chikatetsu'], 'ちかてつ', 'kereta bawah tanah', 'word', true, 'Pelajaran 5'),
('words', '新幹線', ARRAY['shinkansen'], 'しんかんせん', 'Shinkansen, kereta cepat', 'word', true, 'Pelajaran 5'),
('words', '自転車', ARRAY['jitensha'], 'じてんしゃ', 'sepeda', 'word', true, 'Pelajaran 5'),
('words', '人', ARRAY['hito'], 'ひと', 'orang', 'word', true, 'Pelajaran 5'),
('words', '友達', ARRAY['tomodachi'], 'ともだち', 'teman', 'word', true, 'Pelajaran 5'),
('words', '彼', ARRAY['kare'], 'かれ', 'dia (laki-laki)', 'word', true, 'Pelajaran 5'),
('words', '彼女', ARRAY['kanojo'], 'かのじょ', 'dia (perempuan), pacar', 'word', true, 'Pelajaran 5'),
('words', '家族', ARRAY['kazoku'], 'かぞく', 'keluarga', 'word', true, 'Pelajaran 5'),
('words', '先週', ARRAY['senshuu', 'senshu'], 'せんしゅう', 'minggu lalu', 'word', true, 'Pelajaran 5'),
('words', '今週', ARRAY['konshuu', 'konshu'], 'こんしゅう', 'minggu ini', 'word', true, 'Pelajaran 5'),
('words', '来週', ARRAY['raishuu', 'raishu'], 'らいしゅう', 'minggu depan', 'word', true, 'Pelajaran 5'),
('words', '先月', ARRAY['sengetsu'], 'せんげつ', 'bulan lalu', 'word', true, 'Pelajaran 5'),
('words', '今月', ARRAY['kongetsu'], 'こんげつ', 'bulan ini', 'word', true, 'Pelajaran 5'),
('words', '来月', ARRAY['raigetsu'], 'らいげつ', 'bulan depan', 'word', true, 'Pelajaran 5'),
('words', '去年', ARRAY['kyonen'], 'きょねん', 'tahun lalu', 'word', true, 'Pelajaran 5'),
('words', '来年', ARRAY['rainen'], 'らいねん', 'tahun depan', 'word', true, 'Pelajaran 5'),
('words', '誕生日', ARRAY['tanjoubi', 'tanjobi'], 'たんじょうび', 'hari ulang tahun', 'word', true, 'Pelajaran 5'),
('words', '卵', ARRAY['tamago'], 'たまご', 'telur', 'word', true, 'Pelajaran 6'),
('words', '肉', ARRAY['niku'], 'にく', 'daging', 'word', true, 'Pelajaran 6'),
('words', '魚', ARRAY['sakana'], 'さかな', 'ikan', 'word', true, 'Pelajaran 6'),
('words', '野菜', ARRAY['yasai'], 'やさい', 'sayur', 'word', true, 'Pelajaran 6'),
('words', '果物', ARRAY['kudamono'], 'くだもの', 'buah-buahan', 'word', true, 'Pelajaran 6'),
('words', '水', ARRAY['mizu'], 'みず', 'air', 'word', true, 'Pelajaran 6'),
('words', 'お茶', ARRAY['ocha'], 'おちゃ', 'teh, teh Jepang', 'word', true, 'Pelajaran 6'),
('words', '紅茶', ARRAY['koucha', 'kocha'], 'こうちゃ', 'teh hitam', 'word', true, 'Pelajaran 6'),
('words', '牛乳', ARRAY['gyuunyuu', 'gyunyu'], 'ぎゅうにゅう', 'susu', 'word', true, 'Pelajaran 6'),
('words', 'お酒', ARRAY['osake'], 'おさけ', 'bir / minuman keras / sake', 'word', true, 'Pelajaran 6'),
('words', '手紙', ARRAY['tegami'], 'てがみ', 'surat', 'word', true, 'Pelajaran 6'),
('words', '写真', ARRAY['shashin'], 'しゃしん', 'foto', 'word', true, 'Pelajaran 6'),
('words', '店', ARRAY['mise'], 'みせ', 'toko', 'word', true, 'Pelajaran 6'),
('words', '庭', ARRAY['niwa'], 'にわ', 'halaman, kebun', 'word', true, 'Pelajaran 6'),
('words', '宿題', ARRAY['shukudai'], 'しゅくだい', 'pekerjaan rumah (PR)', 'word', true, 'Pelajaran 6'),
('words', '時々', ARRAY['tokidoki'], 'ときどき', 'kadang-kadang', 'word', true, 'Pelajaran 6'),
('words', '切ります', ARRAY['kirimasu'], 'きります', 'memotong, menggunting', 'word', true, 'Pelajaran 7'),
('words', '送ります', ARRAY['okurimasu'], 'おくります', 'mengirim', 'word', true, 'Pelajaran 7'),
('words', 'あげます', ARRAY['agemasu'], 'あげます', 'memberikan', 'word', false, 'Pelajaran 7'),
('words', 'もらいます', ARRAY['moraimasu'], 'もらいます', 'mendapatkan, menerima', 'word', false, 'Pelajaran 7'),
('words', '貸します', ARRAY['kashimasu'], 'かします', 'meminjamkan, menyewakan', 'word', true, 'Pelajaran 7'),
('words', '借ります', ARRAY['karimasu'], 'かります', 'meminjam, menyewa', 'word', true, 'Pelajaran 7'),
('words', '教えます', ARRAY['oshiemasu'], 'おしえます', 'mengajar', 'word', true, 'Pelajaran 7'),
('words', '習います', ARRAY['naraimasu'], 'ならいます', 'belajar (dari seseorang)', 'word', true, 'Pelajaran 7'),
('words', 'かけます', ARRAY['kakemasu'], 'かけます', 'menelepon [でんわを～]', 'word', false, 'Pelajaran 7'),
('words', '手', ARRAY['te'], 'て', 'tangan', 'word', true, 'Pelajaran 7'),
('words', '箸', ARRAY['hashi'], 'はし', 'sumpit', 'word', true, 'Pelajaran 7'),
('words', '花', ARRAY['hana'], 'はな', 'bunga', 'word', true, 'Pelajaran 7'),
('words', '父', ARRAY['chichi'], 'ちち', 'bapak, ayah (sendiri)', 'word', true, 'Pelajaran 7'),
('words', '母', ARRAY['haha'], 'はは', 'ibu (sendiri)', 'word', true, 'Pelajaran 7'),
('words', 'ハンサムな', ARRAY['hansamu', 'hansamuna'], 'ハンサム', 'tampan, gagah, ganteng', 'word', false, 'Pelajaran 8'),
('words', 'きれいな', ARRAY['kirei', 'kireina'], 'きれい', 'cantik, bersih', 'word', false, 'Pelajaran 8'),
('words', '静かな', ARRAY['shizuka', 'shizukana'], 'しずか', 'sunyi, tenang', 'word', true, 'Pelajaran 8'),
('words', '有名な', ARRAY['yuumei', 'yumei', 'yuumeina'], 'ゆうめい', 'terkenal', 'word', true, 'Pelajaran 8'),
('words', '親切な', ARRAY['shinsetsu', 'shinsetsuna'], 'しんせつ', 'baik hati, ramah', 'word', true, 'Pelajaran 8'),
('words', '元気な', ARRAY['genki', 'genkina'], 'げんき', 'sehat walafiat, bersemangat', 'word', true, 'Pelajaran 8'),
('words', '大きい', ARRAY['ookii', 'oki'], 'おおきい', 'besar', 'word', true, 'Pelajaran 8'),
('words', '小さい', ARRAY['chiisai'], 'ちいさい', 'kecil', 'word', true, 'Pelajaran 8'),
('words', '新しい', ARRAY['atarashii'], 'あたらしい', 'baru', 'word', true, 'Pelajaran 8'),
('words', '古い', ARRAY['furui'], 'ふるい', 'lama, tua, kuno', 'word', true, 'Pelajaran 8'),
('words', 'いい', ARRAY['ii', 'yoi'], 'いい', 'baik, bagus', 'word', false, 'Pelajaran 8'),
('words', '悪い', ARRAY['warui'], 'わるい', 'buruk, jelek', 'word', true, 'Pelajaran 8'),
('words', '暑い', ARRAY['atsui'], 'あつい', 'panas (suhu udara)', 'word', true, 'Pelajaran 8'),
('words', '寒い', ARRAY['samui'], 'さむい', 'dingin (suhu udara)', 'word', true, 'Pelajaran 8'),
('words', '冷たい', ARRAY['tsumetai'], 'つめたい', 'dingin (benda/rasa)', 'word', true, 'Pelajaran 8'),
('words', '難しい', ARRAY['muzukashii'], 'むずかしい', 'sulit, susah', 'word', true, 'Pelajaran 8'),
('words', '易しい', ARRAY['yasashii'], 'やさしい', 'mudah, gampang', 'word', true, 'Pelajaran 8'),
('words', '高い', ARRAY['takai'], 'たかい', 'mahal, tinggi', 'word', true, 'Pelajaran 8'),
('words', '安い', ARRAY['yasui'], 'やすい', 'murah', 'word', true, 'Pelajaran 8'),
('words', '山', ARRAY['yama'], 'やま', 'gunung', 'word', true, 'Pelajaran 8'),
('words', '食べ物', ARRAY['tabemono'], 'たべもの', 'makanan', 'word', true, 'Pelajaran 8'),
('words', '好きな', ARRAY['suki', 'sukina'], 'すき', 'suka, gemar', 'word', true, 'Pelajaran 9'),
('words', '嫌いな', ARRAY['kirai', 'kiraina'], 'きらい', 'tidak suka, benci', 'word', true, 'Pelajaran 9'),
('words', '上手な', ARRAY['jouzu', 'joju', 'jouzuna'], 'じょうず', 'pandai, pintar, mahir', 'word', true, 'Pelajaran 9'),
('words', '下手な', ARRAY['heta', 'hetana'], 'へた', 'tidak pandai, kurang mahir', 'word', true, 'Pelajaran 9'),
('words', '飲み物', ARRAY['nomimono'], 'のみもの', 'minuman', 'word', true, 'Pelajaran 9'),
('words', '料理', ARRAY['ryouri', 'ryori'], 'りょうり', 'masakan, hidangan', 'word', true, 'Pelajaran 9'),
('words', '野球', ARRAY['yakyuu', 'yakyu'], 'やきゅう', 'baseball', 'word', true, 'Pelajaran 9'),
('words', '旅行', ARRAY['ryokou', 'ryoko'], 'りょこう', 'tamasya, perjalanan, traveling', 'word', true, 'Pelajaran 9'),
('words', '音楽', ARRAY['ongaku'], 'おんがく', 'musik', 'word', true, 'Pelajaran 9'),
('words', '歌', ARRAY['uta'], 'うた', 'lagu', 'word', true, 'Pelajaran 9'),
('words', '歌舞伎', ARRAY['kabuki'], 'かぶき', 'kabuki (seni teater Jepang)', 'word', true, 'Pelajaran 9'),
('words', '絵', ARRAY['e'], 'え', 'gambar, lukisan', 'word', true, 'Pelajaran 9'),
('words', '字', ARRAY['ji'], 'じ', 'huruf, aksara', 'word', true, 'Pelajaran 9'),
('words', '漢字', ARRAY['kanji'], 'かんじ', 'huruf Kanji', 'word', true, 'Pelajaran 9'),
('words', '細かいお金', ARRAY['komakai okane'], 'こまかいおかね', 'uang kecil, receh', 'word', true, 'Pelajaran 9'),
('words', '時間', ARRAY['jikan'], 'じかん', 'jam, waktu', 'word', true, 'Pelajaran 9'),
('words', '用事', ARRAY['youji', 'yoji'], 'ようじ', 'urusan', 'word', true, 'Pelajaran 9'),
('words', '約束', ARRAY['yakusoku'], 'やくそく', 'janji', 'word', true, 'Pelajaran 9'),
('words', 'ご主人', ARRAY['goshujin'], 'ごしゅじん', 'suami (orang lain)', 'word', true, 'Pelajaran 9'),
('words', '夫', ARRAY['otto'], 'おっと', 'suami (sendiri)', 'word', true, 'Pelajaran 9'),
('words', '奥さん', ARRAY['okusan'], 'おくさん', 'istri (orang lain)', 'word', true, 'Pelajaran 9'),
('words', '妻', ARRAY['tsuma'], 'つま', 'istri (sendiri)', 'word', true, 'Pelajaran 9'),
('words', '子供', ARRAY['kodomo'], 'こども', 'anak', 'word', true, 'Pelajaran 9'),
('words', '少し', ARRAY['sukoshi'], 'すこし', 'sedikit', 'word', true, 'Pelajaran 9'),
('words', '全然', ARRAY['zenzen'], 'ぜんぜん', 'sama sekali tidak', 'word', true, 'Pelajaran 9'),
('words', '早く', ARRAY['hayaku'], 'はやく', 'dengan cepat, pagi-pagi', 'word', true, 'Pelajaran 9'),
('words', '男の人', ARRAY['otoko no hito'], 'おとこのひと', 'orang laki-laki, pria', 'word', true, 'Pelajaran 10'),
('words', '女の人', ARRAY['onna no hito'], 'おんなのひと', 'orang perempuan, wanita', 'word', true, 'Pelajaran 10'),
('words', '男の子', ARRAY['otoko no ko'], 'おとこのこ', 'anak laki-laki', 'word', true, 'Pelajaran 10'),
('words', '女の子', ARRAY['onna no ko'], 'おんなのこ', 'anak perempuan', 'word', true, 'Pelajaran 10'),
('words', '犬', ARRAY['inu'], 'いぬ', 'anjing', 'word', true, 'Pelajaran 10'),
('words', '猫', ARRAY['neko'], 'ねこ', 'kucing', 'word', true, 'Pelajaran 10'),
('words', '象', ARRAY['zou', 'zo'], 'ぞう', 'gajah', 'word', true, 'Pelajaran 10'),
('words', '木', ARRAY['ki'], 'き', 'pohon, kayu', 'word', true, 'Pelajaran 10'),
('words', '物', ARRAY['mono'], 'もの', 'barang, benda', 'word', true, 'Pelajaran 10'),
('words', '電池', ARRAY['denchi'], 'でんち', 'baterai', 'word', true, 'Pelajaran 10'),
('words', '箱', ARRAY['hako'], 'はこ', 'kotak', 'word', true, 'Pelajaran 10'),
('words', '冷蔵庫', ARRAY['reizouko', 'rezoko'], 'れいぞうこ', 'kulkas, lemari es', 'word', true, 'Pelajaran 10'),
('words', '棚', ARRAY['tana'], 'たな', 'lemari, rak', 'word', true, 'Pelajaran 10'),
('words', '窓', ARRAY['mado'], 'まど', 'jendela', 'word', true, 'Pelajaran 10'),
('words', '公園', ARRAY['kouen', 'koen'], 'こうえん', 'taman', 'word', true, 'Pelajaran 10'),
('words', '喫茶店', ARRAY['kissaten'], 'きっさてん', 'kedai kopi, cafe', 'word', true, 'Pelajaran 10'),
('words', '～屋', ARRAY['ya', '~ya'], '～や', 'toko ~', 'word', true, 'Pelajaran 10'),
('words', '乗り場', ARRAY['noriba'], 'のりば', 'tempat naik kendaraan', 'word', true, 'Pelajaran 10'),
('words', '県', ARRAY['ken'], 'けん', 'prefektur', 'word', true, 'Pelajaran 10'),
('words', '上', ARRAY['ue'], 'うえ', 'atas', 'word', true, 'Pelajaran 10'),
('words', '下', ARRAY['shita'], 'した', 'bawah', 'word', true, 'Pelajaran 10'),
('words', '前', ARRAY['mae'], 'まえ', 'depan, muka', 'word', true, 'Pelajaran 10'),
('words', '右', ARRAY['migi'], 'みぎ', 'kanan', 'word', true, 'Pelajaran 10'),
('words', '左', ARRAY['hidari'], 'ひだり', 'kiri', 'word', true, 'Pelajaran 10'),
('words', '中', ARRAY['naka'], 'なか', 'dalam, tengah', 'word', true, 'Pelajaran 10'),
('words', '外', ARRAY['soto'], 'そと', 'luar', 'word', true, 'Pelajaran 10'),
('words', '隣', ARRAY['tonari'], 'となり', 'sebelah, samping', 'word', true, 'Pelajaran 10'),
('words', '近く', ARRAY['chikaku'], 'ちかく', 'dekat', 'word', true, 'Pelajaran 10'),
('words', '間', ARRAY['aida'], 'あいだ', 'antara', 'word', true, 'Pelajaran 10'),
('words', 'あります', ARRAY['arimasu'], 'あります', 'ada (benda mati)', 'word', false, 'Pelajaran 10'),
('words', 'います', ARRAY['imasu'], 'います', 'ada (makhluk hidup)', 'word', false, 'Pelajaran 10'),
('words', '休みます', ARRAY['yasumimasu'], 'やすみます', 'tidak masuk kerja [かいしゃを～]', 'word', true, 'Pelajaran 11'),
('words', '一つ', ARRAY['hitotsu'], 'ひとつ', 'satu buah', 'word', true, 'Pelajaran 11'),
('words', '二つ', ARRAY['futatsu'], 'ふたつ', 'dua buah', 'word', true, 'Pelajaran 11'),
('words', '三つ', ARRAY['mittsu'], 'みっつ', 'tiga buah', 'word', true, 'Pelajaran 11'),
('words', '四つ', ARRAY['yottsu'], 'よっつ', 'empat buah', 'word', true, 'Pelajaran 11'),
('words', '五つ', ARRAY['itsutsu'], 'いつつ', 'lima buah', 'word', true, 'Pelajaran 11'),
('words', '六つ', ARRAY['muttsu'], 'むっつ', 'enam buah', 'word', true, 'Pelajaran 11'),
('words', '七つ', ARRAY['nanatsu'], 'ななつ', 'tujuh buah', 'word', true, 'Pelajaran 11'),
('words', '八つ', ARRAY['yattsu'], 'やっつ', 'delapan buah', 'word', true, 'Pelajaran 11'),
('words', '九つ', ARRAY['kokonotsu'], 'ここのつ', 'sembilan buah', 'word', true, 'Pelajaran 11'),
('words', '十', ARRAY['too', 'to'], 'とお', 'sepuluh buah', 'word', true, 'Pelajaran 11'),
('words', 'いくつ', ARRAY['ikutsu'], 'いくつ', 'berapa buah', 'word', false, 'Pelajaran 11'),
('words', '一人', ARRAY['hitori'], 'ひとり', 'seorang, 1 orang', 'word', true, 'Pelajaran 11'),
('words', '二人', ARRAY['futari'], 'ふたり', 'dua orang', 'word', true, 'Pelajaran 11'),
('words', '～枚', ARRAY['mai', '~mai'], '～まい', 'lembar, helai', 'word', true, 'Pelajaran 11'),
('words', '～回', ARRAY['kai', '~kai'], '～かい', 'kali, frekuensi', 'word', true, 'Pelajaran 11'),
('words', '～時間', ARRAY['jikan', '~jikan'], '～じかん', 'durasi jam', 'word', true, 'Pelajaran 11'),
('words', '～週間', ARRAY['shuukan', '~shuukan'], '～しゅうかん', 'durasi minggu', 'word', true, 'Pelajaran 11'),
('words', '～か月', ARRAY['kagetsu', '~kagetsu'], '～かげつ', 'durasi bulan', 'word', true, 'Pelajaran 11'),
('words', '～年', ARRAY['nen', '~nen'], '～ねん', 'durasi tahun', 'word', true, 'Pelajaran 11'),
('words', 'かかります', ARRAY['kakarimasu'], 'かかります', 'memakan, perlu (waktu/uang)', 'word', false, 'Pelajaran 11'),
('words', '～台', ARRAY['dai', '~dai'], '～だい', 'unit, buah (mesin/mobil)', 'word', true, 'Pelajaran 11'),
('words', '切手', ARRAY['kitte'], 'きって', 'perangko', 'word', true, 'Pelajaran 11'),
('words', '封筒', ARRAY['fuutou', 'futo'], 'ふうとう', 'amplop', 'word', true, 'Pelajaran 11'),
('words', '両親', ARRAY['ryoushin', 'ryoshin'], 'りょうしん', 'orang tua', 'word', true, 'Pelajaran 11'),
('words', '兄弟', ARRAY['kyoudai', 'kyodai'], 'きょうだい', 'saudara kandung', 'word', true, 'Pelajaran 11'),
('words', '兄', ARRAY['ani'], 'あに', 'kakak laki-laki (sendiri)', 'word', true, 'Pelajaran 11'),
('words', 'お兄さん', ARRAY['oniisan'], 'おにいさん', 'kakak laki-laki (orang lain)', 'word', true, 'Pelajaran 11'),
('words', '姉', ARRAY['ane'], 'あね', 'kakak perempuan (sendiri)', 'word', true, 'Pelajaran 11'),
('words', 'お姉さん', ARRAY['oneesan'], 'おねえさん', 'kakak perempuan (orang lain)', 'word', true, 'Pelajaran 11'),
('words', '弟', ARRAY['otouto', 'ototo'], 'おとうと', 'adik laki-laki (sendiri)', 'word', true, 'Pelajaran 11'),
('words', '弟さん', ARRAY['otoutosan', 'ototosan'], 'おとうとさん', 'adik laki-laki (orang lain)', 'word', true, 'Pelajaran 11'),
('words', '妹', ARRAY['imouto', 'imoto'], 'いもうと', 'adik perempuan (sendiri)', 'word', true, 'Pelajaran 11'),
('words', '妹さん', ARRAY['imoutosan', 'imotosan'], 'いもうとさん', 'adik perempuan (orang lain)', 'word', true, 'Pelajaran 11'),
('words', '外国', ARRAY['gaikoku'], 'がいこく', 'luar negeri', 'word', true, 'Pelajaran 11'),
('words', '留学生', ARRAY['ryuugakusei', 'ryugakusei'], 'りゅうがくせい', 'pelajar asing, mahasiswa asing', 'word', true, 'Pelajaran 11'),
('words', '多い', ARRAY['ooi', 'oi'], 'おおい', 'banyak (orang/barang)', 'word', true, 'Pelajaran 12'),
('words', '少ない', ARRAY['sukunai'], 'すくない', 'sedikit (orang/barang)', 'word', true, 'Pelajaran 12'),
('words', '刺身', ARRAY['sashimi'], 'さしみ', 'sashimi (irisan ikan mentah)', 'word', true, 'Pelajaran 12'),
('words', '紅葉', ARRAY['momiji'], 'もみじ', 'maple, daun musim gugur', 'word', true, 'Pelajaran 12'),
('words', '簡単な', ARRAY['kantan', 'kantanna'], 'かんたん', 'mudah, gampang, simpel', 'word', true, 'Pelajaran 12'),
('words', '近い', ARRAY['chikai'], 'ちかい', 'dekat', 'word', true, 'Pelajaran 12'),
('words', '遠い', ARRAY['tooi', 'toi'], 'とおい', 'jauh', 'word', true, 'Pelajaran 12'),
('words', '速い', ARRAY['hayai'], 'はやい', 'cepat', 'word', true, 'Pelajaran 12'),
('words', '早い', ARRAY['hayai'], 'はやい', 'pagi, awal', 'word', true, 'Pelajaran 12'),
('words', '遅い', ARRAY['osoi'], 'おそい', 'lambat, telat', 'word', true, 'Pelajaran 12'),
('words', '暖かい', ARRAY['atatakai'], 'あたたかい', 'hangat (suhu udara)', 'word', true, 'Pelajaran 12'),
('words', '温かい', ARRAY['atatakai'], 'あたたかい', 'hangat (benda/makanan)', 'word', true, 'Pelajaran 12'),
('words', '涼しい', ARRAY['suzushii'], 'すずしい', 'sejuk', 'word', true, 'Pelajaran 12'),
('words', '甘い', ARRAY['amai'], 'あまい', 'manis', 'word', true, 'Pelajaran 12'),
('words', '辛い', ARRAY['karai'], 'からい', 'pedas, asin kuat', 'word', true, 'Pelajaran 12'),
('words', '重い', ARRAY['omoi'], 'おもい', 'berat', 'word', true, 'Pelajaran 12'),
('words', '軽い', ARRAY['karui'], 'かるい', 'ringan', 'word', true, 'Pelajaran 12'),
('words', '季節', ARRAY['kisetsu'], 'きせつ', 'musim', 'word', true, 'Pelajaran 12'),
('words', '春', ARRAY['haru'], 'はる', 'musim semi', 'word', true, 'Pelajaran 12'),
('words', '夏', ARRAY['natsu'], 'なつ', 'musim panas', 'word', true, 'Pelajaran 12'),
('words', '秋', ARRAY['aki'], 'あき', 'musim gugur', 'word', true, 'Pelajaran 12'),
('words', '冬', ARRAY['fuyu'], 'ふゆ', 'musim dingin', 'word', true, 'Pelajaran 12'),
('words', '天気', ARRAY['tenki'], 'てんき', 'cuaca', 'word', true, 'Pelajaran 12'),
('words', '雨', ARRAY['ame'], 'あめ', 'hujan', 'word', true, 'Pelajaran 12'),
('words', '雪', ARRAY['yuki'], 'ゆき', 'salju', 'word', true, 'Pelajaran 12'),
('words', '曇り', ARRAY['kumori'], 'くもり', 'mendung, berawan', 'word', true, 'Pelajaran 12'),
('words', '空港', ARRAY['kuukou', 'kuko'], 'くうこう', 'bandara', 'word', true, 'Pelajaran 12'),
('words', '海', ARRAY['umi'], 'うみ', 'laut, pantai', 'word', true, 'Pelajaran 12'),
('words', '世界', ARRAY['sekai'], 'せかい', 'dunia', 'word', true, 'Pelajaran 12'),
('words', '祭り', ARRAY['omatsuri', 'matsuri'], 'おまつり', 'perayaan, festival', 'word', true, 'Pelajaran 12'),
('words', '豚肉', ARRAY['butaniku'], 'ぶたにく', 'daging babi', 'word', true, 'Pelajaran 12'),
('words', '鶏肉', ARRAY['toriniku'], 'とりにく', 'daging ayam', 'word', true, 'Pelajaran 12'),
('words', '牛肉', ARRAY['gyuuniku', 'gyuniku'], 'ぎゅうにく', 'daging sapi', 'word', true, 'Pelajaran 12'),
('words', '生け花', ARRAY['ikebana'], 'いけばな', 'seni merangkai bunga', 'word', true, 'Pelajaran 12'),
('words', '初めて', ARRAY['hajimete'], 'はじめて', 'untuk pertama kali', 'word', true, 'Pelajaran 12'),
('words', '遊びます', ARRAY['asobimasu'], 'あそびます', 'bermain, bersenang-senang', 'word', true, 'Pelajaran 13'),
('words', '泳ぎます', ARRAY['oyogimasu'], 'およぎます', 'berenang', 'word', true, 'Pelajaran 13'),
('words', '迎えます', ARRAY['mukaemasu'], 'むかえます', 'menjemput, menyambut', 'word', true, 'Pelajaran 13'),
('words', '疲れます', ARRAY['tsukaremasu'], 'つかれます', 'lelah, letih', 'word', true, 'Pelajaran 13'),
('words', '結婚します', ARRAY['kekkonshimasu', 'kekkonsimasu'], 'けっこんします', 'menikah', 'word', true, 'Pelajaran 13'),
('words', '買い物します', ARRAY['kaimonoshimasu', 'kaimonosimasu'], 'かいものします', 'berbelanja', 'word', true, 'Pelajaran 13'),
('words', '食事します', ARRAY['shokujishimasu', 'syokujisimasu'], 'しょくじします', 'makan (bersama)', 'word', true, 'Pelajaran 13'),
('words', '散歩します', ARRAY['sanposhimasu', 'sanposimasu'], 'さんぽします', 'berjalan-jalan [こうえんを～]', 'word', true, 'Pelajaran 13'),
('words', '大変な', ARRAY['taihen', 'taihenna'], 'たいへん', 'berat, susah, gawat', 'word', true, 'Pelajaran 13'),
('words', '欲しい', ARRAY['hoshii', 'hosi'], 'ほしい', 'ingin, mau (benda)', 'word', true, 'Pelajaran 13'),
('words', '広い', ARRAY['hiroi'], 'ひろい', 'luas, lebar', 'word', true, 'Pelajaran 13'),
('words', '狭い', ARRAY['semai'], 'せまい', 'sempit', 'word', true, 'Pelajaran 13'),
('words', '美術', ARRAY['bijutsu'], 'びじゅつ', 'seni rupa, keindahan', 'word', true, 'Pelajaran 13'),
('words', '釣り', ARRAY['tsuri'], 'つり', 'memancing', 'word', true, 'Pelajaran 13'),
('words', '週末', ARRAY['shuumatsu', 'shumatsu'], 'しゅうまつ', 'akhir pekan, weekend', 'word', true, 'Pelajaran 13'),
('words', 'つけます', ARRAY['tsukemasu'], 'つけます', 'menyalakan, memasang [でんきを～]', 'word', false, 'Pelajaran 14'),
('words', '消します', ARRAY['keshimasu', 'kesimasu'], 'けします', 'mematikan, memadamkan [でんきを～]', 'word', true, 'Pelajaran 14'),
('words', '開けます', ARRAY['akemasu'], 'あけます', 'membuka [ドアを～]', 'word', true, 'Pelajaran 14'),
('words', '閉めます', ARRAY['shimemasu', 'simemasu'], 'しめます', 'menutup [ドアを～]', 'word', true, 'Pelajaran 14'),
('words', '急ぎます', ARRAY['isogimasu'], 'いそぎます', 'buru-buru, bergegas', 'word', true, 'Pelajaran 14'),
('words', '待ちます', ARRAY['machimasu'], 'まちます', 'menunggu', 'word', true, 'Pelajaran 14'),
('words', '持ちます', ARRAY['mochimasu'], 'もちます', 'membawa, memegang', 'word', true, 'Pelajaran 14'),
('words', '取ります', ARRAY['torimasu'], 'とります', 'mengambil', 'word', true, 'Pelajaran 14'),
('words', '手伝います', ARRAY['tetsudaimasu'], 'てつだいます', 'membantu, menolong', 'word', true, 'Pelajaran 14'),
('words', '呼びます', ARRAY['yobimasu'], 'よびます', 'memanggil (taksi/orang)', 'word', true, 'Pelajaran 14'),
('words', '話します', ARRAY['hanashimasu', 'hanasimasu'], 'はなします', 'berbicara', 'word', true, 'Pelajaran 14'),
('words', '使います', ARRAY['tsukaimasu'], 'つかいます', 'memakai, menggunakan', 'word', true, 'Pelajaran 14'),
('words', '止めます', ARRAY['tomemasu'], 'とめます', 'menghentikan, memarkir [くるまを～]', 'word', true, 'Pelajaran 14'),
('words', '見せます', ARRAY['misemasu'], 'みせます', 'memperlihatkan, menunjukkan', 'word', true, 'Pelajaran 14'),
('words', '教えます', ARRAY['oshiemasu', 'osiemasu'], 'おしえます', 'memberitahukan, mengajar [じゅうしょを～]', 'word', true, 'Pelajaran 14'),
('words', '座ります', ARRAY['suwarimasu'], 'すわります', 'duduk', 'word', true, 'Pelajaran 14'),
('words', '立ちます', ARRAY['tachimasu'], 'たちます', 'berdiri', 'word', true, 'Pelajaran 14'),
('words', '入ります', ARRAY['hairimasu'], 'はいります', 'masuk [きっさてんに～]', 'word', true, 'Pelajaran 14'),
('words', '出ます', ARRAY['demasu'], 'でます', 'keluar [きっさてんを～]', 'word', true, 'Pelajaran 14'),
('words', '降ります', ARRAY['furimasu'], 'ふります', 'turun (hujan/salju) [あめが～]', 'word', true, 'Pelajaran 14'),
('words', 'コピーします', ARRAY['kopiishimasu', 'kopiisimasu'], 'コピーします', 'memfotokopi', 'word', false, 'Pelajaran 14'),
('words', '電気', ARRAY['denki'], 'でんき', 'listrik, lampu', 'word', true, 'Pelajaran 14'),
('words', '住所', ARRAY['juusho', 'jusho'], 'じゅうしょ', 'alamat', 'word', true, 'Pelajaran 14'),
('words', '地図', ARRAY['chizu'], 'ちず', 'peta', 'word', true, 'Pelajaran 14'),
('words', '砂糖', ARRAY['satou', 'sato'], 'さとう', 'gula', 'word', true, 'Pelajaran 14'),
('words', '問題', ARRAY['mondai'], 'もんだい', 'masalah, soal', 'word', true, 'Pelajaran 14'),
('words', '答え', ARRAY['kotae'], 'こたえ', 'jawaban', 'word', true, 'Pelajaran 14'),
('words', '読み方', ARRAY['yomikata'], 'よみかた', 'cara membaca', 'word', true, 'Pelajaran 14'),
('words', '置きます', ARRAY['okimasu'], 'おきます', 'meletakkan, menaruh', 'word', true, 'Pelajaran 15'),
('words', '作ります', ARRAY['tsukurimasu'], 'つくります', 'membuat, memproduksi', 'word', true, 'Pelajaran 15'),
('words', '売ります', ARRAY['urimasu'], 'うります', 'menjual', 'word', true, 'Pelajaran 15'),
('words', '知ります', ARRAY['shirimasu', 'sirimasu'], 'しります', 'mengetahui, mengenal', 'word', true, 'Pelajaran 15'),
('words', '住みます', ARRAY['sumimasu'], 'すみます', 'tinggal, mendiami', 'word', true, 'Pelajaran 15'),
('words', '研究します', ARRAY['kenkyuushimasu', 'kenkyushimasu'], 'けんきゅうします', 'meneliti', 'word', true, 'Pelajaran 15'),
('words', '資料', ARRAY['shiryou', 'shiryo'], 'しりょう', 'data, bahan materi', 'word', true, 'Pelajaran 15'),
('words', '時刻表', ARRAY['jikokuhyou', 'jikokuhyo'], 'じこくひょう', 'jadwal waktu', 'word', true, 'Pelajaran 15'),
('words', '服', ARRAY['fuku'], 'ふく', 'baju, pakaian', 'word', true, 'Pelajaran 15'),
('words', '製品', ARRAY['seihin'], 'せいひん', 'produk, barang buatan', 'word', true, 'Pelajaran 15'),
('words', '経済', ARRAY['keizai'], 'けいざい', 'ekonomi', 'word', true, 'Pelajaran 15'),
('words', '市役所', ARRAY['shiyakusho', 'shiyakusyo'], 'しやくしょ', 'kantor wali kota', 'word', true, 'Pelajaran 15'),
('words', '高校', ARRAY['koukou', 'koko'], 'こうこう', 'SMA (Sekolah Menengah Atas)', 'word', true, 'Pelajaran 15'),
('words', '歯医者', ARRAY['haisha', 'haisya'], 'はいしゃ', 'dokter gigi', 'word', true, 'Pelajaran 15'),
('words', '独身', ARRAY['dokushin', 'dokusin'], 'どくしん', 'bujangan, belum menikah', 'word', true, 'Pelajaran 15'),
('words', '乗ります', ARRAY['norimasu'], 'のります', 'naik kendaraan [でんしゃに～]', 'word', true, 'Pelajaran 16'),
('words', '降ります', ARRAY['orimasu'], 'おります', 'turun dari kendaraan [でんしゃを～]', 'word', true, 'Pelajaran 16'),
('words', '乗り換えます', ARRAY['norikaemasu'], 'のりかえます', 'ganti / pindah kendaraan', 'word', true, 'Pelajaran 16'),
('words', '浴びます', ARRAY['abimasu'], 'あびます', 'mandi [シャワーを～]', 'word', true, 'Pelajaran 16'),
('words', '入れます', ARRAY['iremasu'], 'いれます', 'memasukkan', 'word', true, 'Pelajaran 16'),
('words', '出します', ARRAY['dashimasu', 'dasimasu'], 'だします', 'mengeluarkan, menyerahkan', 'word', true, 'Pelajaran 16'),
('words', '下ろします', ARRAY['oroshimasu', 'orosimasu'], 'おろします', 'menarik uang (dari bank)', 'word', true, 'Pelajaran 16'),
('words', '入ります', ARRAY['hairimasu'], 'はいります', 'masuk universitas [だいがくに～]', 'word', true, 'Pelajaran 16'),
('words', '出ます', ARRAY['demasu'], 'でます', 'lulus / tamat universitas [だいがくを～]', 'word', true, 'Pelajaran 16'),
('words', '押します', ARRAY['oshimasu', 'osimasu'], 'おします', 'menekan, mendorong (tombol)', 'word', true, 'Pelajaran 16'),
('words', '飲みます', ARRAY['nomimasu'], 'のみます', 'minum (minuman keras)', 'word', true, 'Pelajaran 16'),
('words', '始めます', ARRAY['hajimemasu'], 'はじめます', 'memulai', 'word', true, 'Pelajaran 16'),
('words', '見学します', ARRAY['kengakushimasu', 'kengakusimasu'], 'けんがくします', 'mengunjungi, studi banding', 'word', true, 'Pelajaran 16'),
('words', '若い', ARRAY['wakai'], 'わかい', 'muda', 'word', true, 'Pelajaran 16'),
('words', '長い', ARRAY['nagai'], 'ながい', 'panjang', 'word', true, 'Pelajaran 16'),
('words', '短い', ARRAY['mijikai'], 'みじかい', 'pendek', 'word', true, 'Pelajaran 16'),
('words', '明るい', ARRAY['akarui'], 'あかるい', 'terang, cerah', 'word', true, 'Pelajaran 16'),
('words', '暗い', ARRAY['kurai'], 'くらい', 'gelap', 'word', true, 'Pelajaran 16'),
('words', '体', ARRAY['karada'], 'からだ', 'badan, tubuh', 'word', true, 'Pelajaran 16'),
('words', '頭', ARRAY['atama'], 'あたま', 'kepala', 'word', true, 'Pelajaran 16'),
('words', '緑', ARRAY['midori'], 'みどり', 'hijau, tanaman hijau', 'word', true, 'Pelajaran 16'),
('words', '覚えます', ARRAY['oboemasu'], 'おぼえます', 'mengingat, menghafal', 'word', true, 'Pelajaran 17'),
('words', '忘れます', ARRAY['wasuremasu'], 'わすれます', 'lupa', 'word', true, 'Pelajaran 17'),
('words', '払います', ARRAY['haraimasu'], 'はらいます', 'membayar', 'word', true, 'Pelajaran 17'),
('words', '返します', ARRAY['kaeshimasu', 'kaesimasu'], 'かえします', 'mengembalikan', 'word', true, 'Pelajaran 17'),
('words', '出かけます', ARRAY['dekakemasu'], 'でかけます', 'bepergian, keluar rumah', 'word', true, 'Pelajaran 17'),
('words', '飲みます', ARRAY['nomimasu'], 'のみます', 'minum obat [くすりを～]', 'word', true, 'Pelajaran 17'),
('words', '大切な', ARRAY['taisetsu', 'taisetsuna'], 'たいせつ', 'penting, bernilai, berharga', 'word', true, 'Pelajaran 17'),
('words', '大丈夫な', ARRAY['daijoubu', 'daijobu', 'daijoubuna'], 'だいじょうぶ', 'tidak apa-apa, aman', 'word', true, 'Pelajaran 17'),
('words', '危ない', ARRAY['abunai'], 'あぶない', 'berbahaya', 'word', true, 'Pelajaran 17'),
('words', '禁煙', ARRAY['kin-en', 'kinen'], 'きんえん', 'dilarang merokok', 'word', true, 'Pelajaran 17'),
('words', '熱', ARRAY['netsu'], 'ねつ', 'demam, panas', 'word', true, 'Pelajaran 17'),
('words', '病気', ARRAY['byouki', 'byoki'], 'びょうき', 'sakit, penyakit', 'word', true, 'Pelajaran 17'),
('words', '薬', ARRAY['kusuri'], 'くすり', 'obat', 'word', true, 'Pelajaran 17'),
('words', 'できます', ARRAY['dekimasu'], 'できます', 'dapat, bisa, mampu', 'word', false, 'Pelajaran 18'),
('words', '洗います', ARRAY['araimasu'], 'あらいます', 'mencuci', 'word', true, 'Pelajaran 18'),
('words', '弾きます', ARRAY['hikimasu'], 'ひきます', 'memainkan (alat musik petik/piano)', 'word', true, 'Pelajaran 18'),
('words', '歌います', ARRAY['utaimasu'], 'うたいます', 'bernyanyi', 'word', true, 'Pelajaran 18'),
('words', '集めます', ARRAY['atsumemasu'], 'あつめます', 'mengumpulkan', 'word', true, 'Pelajaran 18'),
('words', '捨てます', ARRAY['sutemasu'], 'すてます', 'membuang', 'word', true, 'Pelajaran 18'),
('words', '換えます', ARRAY['kaemasu'], 'かえます', 'mengganti, menukar', 'word', true, 'Pelajaran 18'),
('words', '運転します', ARRAY['untenshimasu', 'untensimasu'], 'うんてんします', 'menyetir, mengemudi', 'word', true, 'Pelajaran 18'),
('words', '予約します', ARRAY['yoyakushimasu', 'yoyakusimasu'], 'よやくします', 'memesan, reservasi', 'word', true, 'Pelajaran 18'),
('words', '現金', ARRAY['genkin'], 'げんきん', 'uang tunai, cash', 'word', true, 'Pelajaran 18'),
('words', '趣味', ARRAY['shumi', 'syumi'], 'しゅみ', 'hobi', 'word', true, 'Pelajaran 18'),
('words', '日記', ARRAY['nikki'], 'にっき', 'catatan harian, diari', 'word', true, 'Pelajaran 18'),
('words', 'お祈り', ARRAY['oinori'], 'おいのり', 'doa', 'word', true, 'Pelajaran 18'),
('words', '課長', ARRAY['kachou', 'kacho'], 'かちょう', 'kepala seksi (seksi)', 'word', true, 'Pelajaran 18'),
('words', '部長', ARRAY['buchou', 'bucho'], 'ぶちょう', 'kepala bagian (bagian)', 'word', true, 'Pelajaran 18'),
('words', '社長', ARRAY['shachou', 'shacho'], 'しゃちょう', 'direktur utama, presiden direktur', 'word', true, 'Pelajaran 18'),
('words', '動物', ARRAY['doubutsu', 'dobutsu'], 'どうぶつ', 'hewan, binatang', 'word', true, 'Pelajaran 18'),
('words', '馬', ARRAY['uma'], 'うま', 'kuda', 'word', true, 'Pelajaran 18'),
('words', '登ります', ARRAY['noborimasu'], 'のぼります', 'mendaki, naik [やまに～]', 'word', true, 'Pelajaran 19'),
('words', '泊まります', ARRAY['tomarimasu'], 'とまります', 'menginap di hotel [ホテルに～]', 'word', true, 'Pelajaran 19'),
('words', '掃除します', ARRAY['soujishimasu', 'sojishimasu'], 'そうじします', 'membersihkan', 'word', true, 'Pelajaran 19'),
('words', '洗濯します', ARRAY['sentakushimasu', 'sentakusimasu'], 'せんたくします', 'mencuci pakaian', 'word', true, 'Pelajaran 19'),
('words', 'なります', ARRAY['narimasu'], 'なります', 'menjadi', 'word', false, 'Pelajaran 19'),
('words', '眠い', ARRAY['nemui'], 'ねむい', 'mengantuk', 'word', true, 'Pelajaran 19'),
('words', '強い', ARRAY['tsuyoi'], 'つよい', 'kuat', 'word', true, 'Pelajaran 19'),
('words', '弱い', ARRAY['yowai'], 'よわい', 'lemah', 'word', true, 'Pelajaran 19'),
('words', '練習', ARRAY['renshuu', 'renshu'], 'れんしゅう', 'latihan', 'word', true, 'Pelajaran 19'),
('words', 'ゴルフ', ARRAY['gorufu'], 'ゴルフ', 'golf', 'word', false, 'Pelajaran 19'),
('words', '相撲', ARRAY['sumou', 'sumo'], 'すもう', 'sumo (gulat Jepang)', 'word', true, 'Pelajaran 19'),
('words', 'お茶', ARRAY['ocha'], 'おちゃ', 'upacara minum teh', 'word', true, 'Pelajaran 19'),
('words', '日', ARRAY['hi'], 'ひ', 'hari, tanggal', 'word', true, 'Pelajaran 19'),
('words', '調子', ARRAY['choushi', 'choshi'], 'ちょうし', 'kondisi, keadaan fisik', 'word', true, 'Pelajaran 19'),
('words', '一度', ARRAY['ichido'], 'いちど', 'sekali, satu kali', 'word', true, 'Pelajaran 19'),
('words', '要ります', ARRAY['irimasu'], 'いります', 'memerlukan [ビザが～]', 'word', true, 'Pelajaran 20'),
('words', '調べます', ARRAY['shirabemasu', 'sirabemasu'], 'しらべます', 'memeriksa, mencari info, meneliti', 'word', true, 'Pelajaran 20'),
('words', '修理します', ARRAY['shuurishimasu', 'syuurisimasu'], 'しゅうりします', 'memperbaiki, mereparasi', 'word', true, 'Pelajaran 20'),
('words', '僕', ARRAY['boku'], 'ぼく', 'aku (informal watashi)', 'word', true, 'Pelajaran 20'),
('words', '君', ARRAY['kimi'], 'きみ', 'kamu (informal anata)', 'word', true, 'Pelajaran 20'),
('words', '～君', ARRAY['kun', '~kun'], '～くん', 'Sdr. (panggilan informal laki-laki)', 'word', true, 'Pelajaran 20'),
('words', 'うん', ARRAY['un'], 'うん', 'ya (informal hai)', 'word', false, 'Pelajaran 20'),
('words', 'ううん', ARRAY['uun'], 'ううん', 'tidak (informal iie)', 'word', false, 'Pelajaran 20'),
('words', '言葉', ARRAY['kotoba'], 'ことば', 'kata, bahasa', 'word', true, 'Pelajaran 20'),
('words', '着物', ARRAY['kimono'], 'きもの', 'kimono (pakaian tradisional)', 'word', true, 'Pelajaran 20'),
('words', 'ビザ', ARRAY['biza'], 'ビザ', 'VISA', 'word', false, 'Pelajaran 20'),
('words', '初め', ARRAY['hajime'], 'はじめ', 'awal, mula-mula', 'word', true, 'Pelajaran 20'),
('words', '終わり', ARRAY['owari'], 'おわり', 'akhir, selesai', 'word', true, 'Pelajaran 20'),
('words', '思います', ARRAY['omoimasu'], 'おもいます', 'mengira, berpikir, berpendapat', 'word', true, 'Pelajaran 21'),
('words', '言います', ARRAY['iimasu'], 'いいます', 'mengatakan, berkata', 'word', true, 'Pelajaran 21'),
('words', '勝ちます', ARRAY['kachimasu'], 'かちます', 'menang', 'word', true, 'Pelajaran 21'),
('words', '負けます', ARRAY['makemasu'], 'まけます', 'kalah', 'word', true, 'Pelajaran 21'),
('words', 'あります', ARRAY['arimasu'], 'あります', 'diadakan [おまつりが～]', 'word', false, 'Pelajaran 21'),
('words', '役に立ちます', ARRAY['yaku ni tachimasu', 'yakunitachimasu'], 'やくにたちます', 'berguna, bermanfaat', 'word', true, 'Pelajaran 21'),
('words', '動きます', ARRAY['ugokimasu'], 'うごきます', 'bergerak, jalan (mesin)', 'word', true, 'Pelajaran 21'),
('words', 'やめます', ARRAY['yamemasu'], 'やめます', 'berhenti (kerja) [かいしゃを～]', 'word', false, 'Pelajaran 21'),
('words', '気をつけます', ARRAY['ki o tsukemasu', 'kiwotsukemasu'], 'きをつけます', 'berwaspada, berhati-hati', 'word', true, 'Pelajaran 21'),
('words', '留学します', ARRAY['ryuugakushimasu', 'ryugakushimasu'], 'りゅうがくします', 'studi di luar negeri', 'word', true, 'Pelajaran 21'),
('words', '着ます', ARRAY['kimasu'], 'きます', 'memakai (baju bagian atas) [シャツを～]', 'word', true, 'Pelajaran 22'),
('words', '履きます', ARRAY['hakimasu'], 'はきます', 'memakai (sepatu, celana) [くつを～]', 'word', true, 'Pelajaran 22'),
('words', 'かぶります', ARRAY['kaburimasu'], 'かぶります', 'memakai (topi) [ぼうしを～]', 'word', false, 'Pelajaran 22'),
('words', 'かけます', ARRAY['kakemasu'], 'かけます', 'memakai (kacamata) [めがねを～]', 'word', false, 'Pelajaran 22'),
('words', 'します', ARRAY['shimasu', 'simasu'], 'します', 'memakai (aksesoris, dasi) [ネクタイを～]', 'word', false, 'Pelajaran 22'),
('words', '生まれます', ARRAY['umaremasu'], 'うまれます', 'lahir', 'word', true, 'Pelajaran 22'),
('words', '帽子', ARRAY['boushi', 'boshi'], 'ぼうし', 'topi', 'word', true, 'Pelajaran 22'),
('words', '眼鏡', ARRAY['megane'], 'めがね', 'kacamata', 'word', true, 'Pelajaran 22'),
('words', 'お弁当', ARRAY['obentou', 'obento'], 'おべんとう', 'bekal makan siang', 'word', true, 'Pelajaran 22'),
('words', '都合', ARRAY['tsugou', 'tsugo'], 'つごう', 'kondisi, keadaan waktu', 'word', true, 'Pelajaran 22'),
('words', '聞きます', ARRAY['kikimasu'], 'ききます', 'bertanya kepada guru [せんせいに～]', 'word', true, 'Pelajaran 23'),
('words', '回します', ARRAY['mawashimasu', 'mawasimasu'], 'まわします', 'memutar', 'word', true, 'Pelajaran 23'),
('words', '引きます', ARRAY['hikimasu'], 'ひきます', 'menarik', 'word', true, 'Pelajaran 23'),
('words', '変えます', ARRAY['kaemasu'], 'かえます', 'mengubah', 'word', true, 'Pelajaran 23'),
('words', '触ります', ARRAY['sawarimasu'], 'さわります', 'menyentuh pintu [ドアに～]', 'word', true, 'Pelajaran 23'),
('words', '出ます', ARRAY['demasu'], 'でます', 'keluar uang kembalian [おつりが～]', 'word', true, 'Pelajaran 23'),
('words', '歩きます', ARRAY['arukimasu'], 'あるきます', 'berjalan kaki', 'word', true, 'Pelajaran 23'),
('words', '渡ります', ARRAY['watarimasu'], 'わたります', 'menyeberang jembatan [はしを～]', 'word', true, 'Pelajaran 23'),
('words', '曲がります', ARRAY['magarimasu'], 'まがります', 'belok ke kanan [みぎへ～]', 'word', true, 'Pelajaran 23'),
('words', '寂しい', ARRAY['sabishii'], 'さびしい', 'sepi, kesepian', 'word', true, 'Pelajaran 23'),
('words', 'お湯', ARRAY['oyu'], 'おゆ', 'air panas', 'word', true, 'Pelajaran 23'),
('words', '音', ARRAY['oto'], 'おと', 'bunyi, suara', 'word', true, 'Pelajaran 23'),
('words', '故障', ARRAY['koshou', 'kosho'], 'こしょう', 'kerusakan (~します : rusak)', 'word', true, 'Pelajaran 23'),
('words', '道', ARRAY['michi'], 'みち', 'jalan', 'word', true, 'Pelajaran 23'),
('words', '交差点', ARRAY['kousaten', 'kosaten'], 'こうさてん', 'perempatan', 'word', true, 'Pelajaran 23'),
('words', '信号', ARRAY['shingou', 'shingo'], 'しんごう', 'lampu lalu lintas', 'word', true, 'Pelajaran 23'),
('words', '角', ARRAY['kado'], 'かど', 'sudut', 'word', true, 'Pelajaran 23'),
('words', '橋', ARRAY['hashi'], 'はし', 'jembatan', 'word', true, 'Pelajaran 23'),
('words', '駐車場', ARRAY['chuushajou', 'chushajo'], 'ちゅうしゃじょう', 'tempat parkir', 'word', true, 'Pelajaran 23'),
('words', '建物', ARRAY['tatemono'], 'たてもの', 'gedung', 'word', true, 'Pelajaran 23'),
('words', 'くれます', ARRAY['kuremasu'], 'くれます', 'memberikan (kepada saya)', 'word', false, 'Pelajaran 24'),
('words', '直します', ARRAY['naoshimasu', 'naosimasu'], 'なおします', 'mengoreksi, memperbaiki', 'word', true, 'Pelajaran 24'),
('words', '連れて行きます', ARRAY['tsurete ikimasu', 'tsureteikimasu'], 'つれていきます', 'membawa, mengajak pergi (orang)', 'word', true, 'Pelajaran 24'),
('words', '連れて来ます', ARRAY['tsurete kimasu', 'tsuretekimasu'], 'つれてきます', 'membawa, mengajak datang (orang)', 'word', true, 'Pelajaran 24'),
('words', '送ります', ARRAY['okurimasu'], 'おくります', 'mengantar orang [ひとを～]', 'word', true, 'Pelajaran 24'),
('words', '紹介します', ARRAY['shoukaishimasu', 'shokaishimasu'], 'しょうかいします', 'memperkenalkan', 'word', true, 'Pelajaran 24'),
('words', '案内します', ARRAY['annaishimasu', 'annaisimasu'], 'あんないします', 'mengantarkan, memandu jalan', 'word', true, 'Pelajaran 24'),
('words', '説明します', ARRAY['setsumeishimasu', 'setsumeisimasu'], 'せつめいします', 'menjelaskan, menerangkan', 'word', true, 'Pelajaran 24'),
('words', 'おじいさん', ARRAY['ojiisan', 'ojiichan'], 'おじいさん', 'kakek (ojiisan / ojiichan)', 'word', false, 'Pelajaran 24'),
('words', 'おばあさん', ARRAY['obaasan', 'obaachan'], 'おばあさん', 'nenek (obaasan / obaachan)', 'word', false, 'Pelajaran 24'),
('words', '準備', ARRAY['junbi'], 'じゅんび', 'persiapan (~します : mempersiapkan)', 'word', true, 'Pelajaran 24'),
('words', '引っ越し', ARRAY['hikkoshi', 'hikkosi'], 'ひっこし', 'pindah rumah (~します : pindah rumah)', 'word', true, 'Pelajaran 24'),
('words', 'お菓子', ARRAY['okashi', 'okasi'], 'おかし', 'kue, makanan ringan, camilan', 'word', true, 'Pelajaran 24'),
('words', 'ホームステイ', ARRAY['houmusutei', 'homestay', 'homusutei'], 'ホームステイ', 'homestay', 'word', false, 'Pelajaran 24'),
('words', '全部', ARRAY['zenbu'], 'ぜんぶ', 'semua, seluruhnya', 'word', true, 'Pelajaran 24'),
('words', '自分で', ARRAY['jibun de', 'jibunde'], 'じぶんで', 'dengan sendiri, sendiri', 'word', true, 'Pelajaran 24'),
('words', 'ほかに', ARRAY['hokani'], 'ほかに', 'selain, yang lain', 'word', false, 'Pelajaran 24'),
('words', '母の日', ARRAY['haha no hi', 'hahanohi'], 'ははのひ', 'Hari Ibu', 'word', true, 'Pelajaran 24'),
('words', '考えます', ARRAY['kangaemasu'], 'かんがえます', 'berpikir, memikirkan', 'word', true, 'Pelajaran 25'),
('words', '着きます', ARRAY['tsukimasu'], 'つきます', 'tiba, sampai [えきに～]', 'word', true, 'Pelajaran 25'),
('words', '取ります', ARRAY['torimasu'], 'とります', 'berumur, lanjut usia [としを～]', 'word', true, 'Pelajaran 25'),
('words', '足ります', ARRAY['tarimasu'], 'たります', 'cukup', 'word', true, 'Pelajaran 25'),
('words', '頑張ります', ARRAY['ganbarimasu'], 'がんばります', 'bersemangat, berusaha keras', 'word', true, 'Pelajaran 25'),
('words', '転勤', ARRAY['tenkin'], 'てんきん', 'pindah ke kantor cabang lain', 'word', true, 'Pelajaran 25'),
('words', '田舎', ARRAY['inaka'], 'いなか', 'desa, kampung halaman', 'word', true, 'Pelajaran 25'),
('words', '億', ARRAY['oku'], 'おく', 'seratus juta (100.000.000)', 'word', true, 'Pelajaran 25'),
('words', '意味', ARRAY['imi'], 'いみ', 'arti, makna', 'word', true, 'Pelajaran 25'),
('words', '暇な', ARRAY['hima', 'himana'], 'ひま', 'waktu luang, senggang', 'word', true, 'Pelajaran 25'),
('words', 'チャンス', ARRAY['chansu'], 'チャンス', 'kesempatan, peluang', 'word', false, 'Pelajaran 25'),
('words', 'もし～たら', ARRAY['moshi ~tara', 'moshitara'], 'もし～たら', 'kalau, jika', 'word', false, 'Pelajaran 25'),
('words', 'いろいろお世話になりました', ARRAY['iroiro osewani narimashita', 'iroiro osewa ni narimashita'], 'いろいろおせわになりました', 'Terima kasih banyak atas segala bantuannya', 'word', true, 'Pelajaran 25'),
('words', 'どうぞお元気で', ARRAY['douzo ogenkide', 'dozo ogenkide'], 'どうぞおげんきで', 'Semoga sehat selalu (salam perpisahan)', 'word', true, 'Pelajaran 25');
